config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sub_tasks
  resources :tags
  resources :tasks do
    resources :sub_tasks, only: %i[create]
  end
  root to: redirect('/tasks')
  post '/fast_task', to: 'tasks#fast_task', as: 'fast_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  belongs_to :task
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  scope :today, -> { where('start_date <= ? AND end_date >= ?', Date.today, Date.today) }
  scope :today_ended, -> { where(finished: false) }
  scope :ended, -> { where(finished: true) }
  scope :task, -> { where(typetask: :task) }
  scope :robot, -> { where(typetask: :robot) }
  scope :waiting, -> { where(status: :waiting) }
  scope :developing, -> { where(status: :developing) }
  scope :testing, -> { where(status: :testing) }
  scope :completed, -> { where(status: :completed) }
  scope :running, -> { where(status: :running) }
  validates :title, presence: true
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :sub_tasks

  enum priority: { low: 'Low', moderate: 'Moderate', important: 'Important', urgent: 'Urgent' }
  enum status: { waiting: 'Waiting', developing: 'Developing', testing: 'Testing', completed: 'Completed', running: 'Running' }
  enum typetask: { robot: 'Robot', task: 'Task' }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :tags
  has_many :sub_tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  layout 'application_tasks'
  before_action :authenticate_user!
  before_action :set_sub_task, only: %i[show edit update destroy]

  def index; end

  def show; end

  def new
      @sub_task = SubTask.new
  end

  def edit; end

  def create
      @task = Task.find(params[:task_id])
      @sub_task = current_user.sub_tasks.build(sub_task_params)
      @sub_task.task_id = @task.id

      if @sub_task.save
        redirect_to request.referrer || root_path
        flash[:success] = 'Sub Task criada com sucesso!'
      else
        redirect_to request.referrer || root_path
        flash[:error] = 'Título não preenchido'
      end
  end

  def update
      if @sub_task.update(sub_task_params)
        redirect_to sub_tasks_path
        flash[:success] = 'Sub Task alterada com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
      @sub_task.destroy
      redirect_to sub_task_path
      flash[:success] = 'Sub Task apagada com sucesso!'
  end

  private

  def set_sub_task
    @sub_task = SubTask.find(params[:id])
  end

  def sub_task_params
    params.require(:sub_task).permit(:title, :finished)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'application_tasks'
  before_action :authenticate_user!
  before_action :set_tag, only: %i[show edit update destroy]

  def index
      @tags = current_user.tags
  end

  def show; end

  def new
      @tag = Tag.new
  end

  def edit; end

  def create
      @tag = current_user.tags.build(tag_params)
      if @tag.save
        redirect_to tags_path
        flash[:success] = 'Tag criada com sucesso'
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
      if @tag.update(tag_params)
        redirect_to tags_path
        flash[:success] = 'Tag alterada com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
      @tag.destroy
      redirect_to tags_path
      flash[:success] = 'Tag apagada com sucesso!'
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout 'application_tasks'
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def index
      filter_tasks
      apply_filters
      order_tasks
  end

  def show; end

  def new
      @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
    @sub_tasks = current_user.sub_tasks.where(task_id: @task.id)
  end

  def create
      @task = current_user.tasks.build(task_params)
      if @task.save
        set_type_task
        redirect_to request.referrer || root_path
        flash[:success] = "#{@type_task} criad#{@sex} com sucesso!"
      else
        render :new, status: :unprocessable_entity
      end
  end

  def fast_task
      @task = current_user.tasks.build(task_params)
      @task.start_date = Date.today
      @task.end_date = Date.today

      if @task.save
        set_type_task
        redirect_to request.referrer || root_path
        flash[:success] = "#{@type_task} criad#{@sex} com sucesso!"
      else
        redirect_to request.referrer || root_path
        flash[:error] = 'Título não preenchido'
      end
  end

  def update
      if @task.update(task_params)
        set_type_task
        redirect_to request.referrer || root_path
        flash[:success] = "#{@type_task} alterad#{@sex} com sucesso!"
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
      @task.destroy
      set_type_task
      redirect_to request.referrer || root_path
      flash[:success] = "#{@type_task} apagad#{@sex} com sucesso!"
  end

  private

  def set_type_task
    if @task.typetask == 'Robô'
      @type_task = 'Robô'
      @sex = 'o'
    else
      @type_task = 'Tarefa'
      @sex = 'a'
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def filter_tasks
    @tasks = current_user.tasks
  end

  def apply_filters
    @tasks = current_user.tasks
    case params[:filter]
    when 'today_tasks'
      @tasks = @tasks.today.today_ended.task
    when 'ended_tasks'
      @tasks = @tasks.ended.task
    when 'tasks'
      @tasks = @tasks.task
    when 'today_robots'
      @tasks = @tasks.today.today_ended.robot
    when 'ended_robots'
      @tasks = @tasks.ended.robot
    when 'robots'
      @tasks = @tasks.robot
    when 'waiting', 'developing', 'testing', 'completed', 'runing'
      @tasks = @tasks.send(params[:filter])
    end
  end

  def order_tasks
    if params[:filter_title].present?
      @tasks = @tasks.where('LOWER(title) LIKE ?', "%#{params[:filter_title].downcase}%")
    end
    @tasks = @tasks.where('start_date >= ?', params[:filter_start_date]) if params[:filter_start_date].present?
    @tasks = @tasks.where('end_date <= ?', params[:filter_end_date]) if params[:filter_end_date].present?
    @tasks = @tasks.where(priority: params[:filter_priority]) if params[:filter_priority].present?
    @tasks = @tasks.where(status: params[:filter_status]) if params[:filter_status].present?
    @tasks = @tasks.where(typetask: params[:filter_typetask]) if params[:filter_typetask].present?
    @tasks = @tasks.order(priority: :desc, finished: :desc)
  end

  def task_params
    params.require(:task).permit(:title, :description, :start_date, :end_date, :result, :priority, :status, :typetask,
                                 :finished, tag_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Todo Robot 2023</span>
    </div>
  </div>
</footer>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= tasks_path %>">
    <div class="sidebar-brand-icon">
      <i class="fas fa-robot"></i>
    </div>
    <div class="sidebar-brand-text mx-2">Todo Robots</div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <%= link_to tasks_path, class: "nav-link" do %>
      <i class="fas fa-chart-line"></i>
      <span>Dashboard</span>
    <% end %>
  </li>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <%= link_to tasks_path, class: "nav-link" do %>
      <i class="fas fa-globe"></i>
      <span>All</span>
    <% end %>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
        aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-user-check"></i>
      <span>Tasks</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to tasks_path(filter: "today_tasks"), class: "collapse-item" do %>
          <i class="fas fa-check"></i>
          <span>Today</span>
        <% end %>
        <%= link_to tasks_path(filter: "tasks"), class: "collapse-item" do %>
          <i class="fas fa-bars"></i>
          <span>All</span>
        <% end %>
        <%= link_to tasks_path(filter: "ended_tasks"), class: "collapse-item" do %>
          <i class="fas fa-hourglass-end"></i>
          <span>Finished</span>
        <% end %>
      </div>
    </div>
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-sun"></i>
        <span>Dialy Bots</span>
      </a>
      <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to tasks_path(filter: "today_robots"), class: "collapse-item" do %>
            <i class="fas fa-check"></i>
            <span>Today</span>
          <% end %>
          <%= link_to tasks_path(filter: "robots"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>All</span>
          <% end %>
          <%= link_to tasks_path(filter: "ended_robots"), class: "collapse-item" do %>
            <i class="fas fa-hourglass-end"></i>
            <span>Finished</span>
          <% end %>
        </div>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
        <i class="fas fa-industry"></i>
        <span>Factory Bots</span>
      </a>
      <div id="collapseUtilities" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to tasks_path(filter: "waiting"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>Waiting</span>
          <% end %>
          <%= link_to tasks_path(filter: "developing"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>Developing</span>
          <% end %>
          <%= link_to tasks_path(filter: "testing"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>Testing</span>
          <% end %>
          <%= link_to tasks_path(filter: "completed"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>Completed</span>
          <% end %>
          <%= link_to tasks_path(filter: "running"), class: "collapse-item" do %>
            <i class="fas fa-bars"></i>
            <span>Running</span>
          <% end %>
        </div>
      </div>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
      <%= link_to tags_path, class: "nav-link" do %>
        <i class="fas fa-tags"></i>
        <span>Tags</span>
      <% end %>
    </li>
    <hr class="sidebar-divider">
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
  </ul>

app/views/layouts/_toastr.html.erb
<% if flash[:success] %>
  <script>
    toastr.success("<%= flash[:success] %>");
  </script>
<% elsif flash[:info] %>
  <script>
    toastr.info("<%= flash[:info] %>");
  </script>
<% elsif flash[:error] %>
  <script>
    toastr.error("<%= flash[:error] %>");
  </script>
<% end %>

app/views/layouts/_topbar.html.erb
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alertas
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Exibir tudo</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Mensagens
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <%= image_tag('robot.png', class: 'img-profile rounded-circle') %>
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a
              problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Exibir tudo</a>
      </div>
    </li>
    <div class="topbar-divider d-none d-sm-block"></div>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>
        <%= image_tag('robot.png', class: 'img-profile rounded-circle') %>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Config
        </a>
        <div class="dropdown-divider"></div>
        <%= button_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          <span class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400">
            <i></i>
          </span>
          Exit
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRobot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_tasks.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo Robot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :javascript %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <%= render 'layouts/sidebar'%>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render 'layouts/topbar' %>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
        <%=render 'layouts/footer'%>
      </div>
    </div>
    <%= turbo_frame_tag "bootstrap_modal" %>
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
    <%=render 'layouts/toastr' %>
  </body>
</html>

app/views/sub_tasks/_form.html.erb
<div class="justify-content-between mt-3">
  <%= form_for(@sub_task) do |f| %>
    <% if f.object.errors.any? %>
      <div class="alert alert-danger">
        <strong>Error:</strong> <%= pluralize(f.object.errors.count, "error") %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="form-actions">
      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/sub_tasks/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "sub_tasks/form", sub_task: @sub_task %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sub_tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>
  <p>
    <strong>Start date:</strong>
    <%= task.start_date %>
  </p>
  <p>
    <strong>End date:</strong>
    <%= task.end_date %>
  </p>
  <p>
    <strong>Result:</strong>
    <%= task.result %>
  </p>
  <p>
    <strong>Finished:</strong>
    <%= task.finished %>
  </p>
</div>

app/views/sub_tasks/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "sub_tasks/form_modal", locals: { sub_task: @sub_task  } %>
<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if f.object.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= pluralize(f.object.errors.count, "error") %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tags/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "tags/form", tag: @tag %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/index.html.erb
<div class="d-flex justify-content-between mb-3">
  <%= link_to "New Tag", new_tag_path, "data-controller":"generic-modal", class: 'btn btn-primary flex-fill mr-2' %>
</div>
<table class="table table-hover">
  <thead>
    <th>Name</th>
    <th></th>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td class="text-truncate" style="max-width: 300px;"><%= tag.name %></td>
        <td class="text-right">
          <%= link_to "Edit", edit_tag_path(tag), "data-controller":"generic-modal", class: 'btn btn-primary' %>
          <%= link_to "Delete", tag_path(tag), method: :delete, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit_task/_form_subtask.html.erb
<div class="d-flex justify-content-between mb-3 mt-3">
  <%= form_with model: SubTask.new, url: task_sub_tasks_path(@task), local: true, class: 'd-flex flex-fill' do |f| %>
    <div class="input-group">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Insira o texto' %>
      <%= f.submit 'Adicionar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<table class="table table-hover">
  <tbody>
    <% @sub_tasks.each do |sub_task| %>
      <tr>
        <td>
          <div class="form-check">
            <%= form_with(model: sub_task, local: true) do |f| %>
              <%= f.check_box :finished, class: "checkbox-toggle form-check-input ml-2" %>
            <% end %>
          </div>
        </td>
        <td><%= sub_task.title %></td>
        <td class="text-right">
          <%= link_to "Editar", edit_sub_task_path(sub_task), "data-controller": "generic-modal", class: "btn btn-primary" %>
          <%= link_to "Excluir", sub_task_path(sub_task), method: :delete, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Deseja realmente excluir?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/index.html.erb
<div class="mb-3">
  <%= form_tag tasks_path, class: 'd-sm-flex', method: :get do %>
    <div class="flex-fill">
      <%= text_field_tag :filter_title, params[:filter_title], class: 'form-control', placeholder: 'Title' %>
    </div>
    <div class="flex-fill ml-2">
      <%= text_field_tag :filter_start_date, params[:filter_start_date], class: 'form-control', placeholder: 'Date Start' %>
    </div>
    <div class="flex-fill ml-2">
      <%= text_field_tag :filter_end_date, params[:filter_end_date], class: 'form-control', placeholder: 'Date End' %>
    </div>
    <div class="flex-fill ml-2">
      <%= select_tag :filter_priority, options_for_select(Task.priorities.map { |key, value| [value.humanize, key] }, params[:filter_priority]), include_blank: 'Priority', class: 'form-control' %>
    </div>
    <div class="flex-fill ml-2">
      <%= select_tag :filter_status, options_for_select(Task.statuses.map { |key, value| [value.humanize, key] }, params[:filter_status]), include_blank: 'Status', class: 'form-control' %>
    </div>
    <div class="flex-fill ml-2 mr-2">
      <%= select_tag :filter_typetask, options_for_select(Task.typetasks.map { |key, value| [value.humanize, key] }, params[:filter_typetask]), include_blank: 'Type', class: 'form-control' %>
    </div>
    <%= submit_tag 'Filter', class: 'btn btn-primary' %>
  <% end %>
</div>
<div class="d-flex justify-content-between mb-3">
  <%= link_to "New Task", new_task_path, "data-controller":"generic-modal", class: 'btn btn-primary flex-fill mr-2' %>
  <%= form_with model: Task.new, url: fast_task_path, method: :post, class: 'd-flex flex-fill' do |f| %>
    <div class="input-group">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Insert Text' %>
      <%= f.submit 'Add', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<table class="table table-hover">
  <thead>
    <th></th>
    <th>Title</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Priority</th>
    <th>Status</th>
    <th>Type</th>
    <th>Tags</th>
    <th></th>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <div class="form-check">
            <%= form_with model: task, class:"form_task " do |f| %>
              <%= f.check_box :finished, class: 'checkbox-toggle form-check-input ml-2' %>
            <% end %>
          </div>
        </td>
        <td class="text-truncate" style="max-width: 300px;"><%= task.title %></td>
        <td><%= task.start_date.strftime("%d/%m/%Y") %></td>
        <td><%= task.end_date.strftime("%d/%m/%Y") %></td>
        <td><%= task.priority.capitalize if task.priority.present? %></td>
        <td><%= task.status.capitalize if task.status.present? %></td>
        <td><%= task.typetask.capitalize if task.typetask.present? %></td>
        <td><%= task.tags.map(&:name).join(', ') %></td>
        <td class="text-right">
          <%= link_to "Edit", edit_task_path(task), "data-controller":"generic-modal", class: 'btn btn-primary' %>
          <%= link_to "Delete", task_path(task), method: :delete, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
        </td>
      </tr>
    <% end %>
    <script src="./task/toggleTask.js"></script>
  </tbody>
</table>